import type { Cents } from '@fc/core';
import { Rng } from '@fc/core';
import type { CapitalFormula, FantasyTeam, MatchupResult, NflPlayer } from '@fc/fantasy';
import {
  buildSchedule,
  computeStandings,
  generatePlayerPool,
  optimalLineup,
  runSnakeDraft,
  samplePlayerWeek,
  weeklyCapital,
} from '@fc/fantasy';
import { Market, type BetKind } from '@fc/markets';
import { Portfolio } from '@fc/portfolio';
import { BOT_BY_KEY, type BotContext, type StrategyBot } from './bots.js';

/**
 * Runs one complete Fantasy Capital season, deterministically from a seed.
 *
 * Weekly ordering contract (no lookahead anywhere):
 *   1. the week's betting slate opens
 *   2. managers trade assets and place bets using capital earned in PRIOR weeks
 *   3. games are played: fantasy scores, matchup results, capital generation
 *      (capital deposited now is investable starting NEXT week)
 *   4. markets realize the week: prices move, player dividends pay to holders,
 *      bets settle against globally shared outcomes
 *   5. NAV snapshot
 */
export interface SeasonConfig {
  seed: number;
  nTeams: number;
  weeks: number;
  formula: CapitalFormula;
  startingBankrollCents: Cents;
  bettingCapPct: number | null;
  desperationEnabled: boolean;
  /** Bot archetype per team; length must equal nTeams. */
  botKeys: string[];
  /** How many players get share markets. */
  listedPlayerCount: number;
  /** League rule: offers above these decimal odds are not listed (e.g. 5 = +400 cap). */
  maxDecimalOdds?: number | null;
}

export interface TeamSeason {
  teamId: string;
  teamName: string;
  botKey: string;
  wins: number;
  losses: number;
  pointsFor: number;
  /** Capital generated by fantasy performance (excludes starting bankroll). */
  capitalGeneratedCents: Cents;
  finalNavCents: Cents;
  /** NAV after each week; index 0 is the starting bankroll. */
  navByWeek: Cents[];
  /** NAV rank (1 = best) after each week, aligned with navByWeek[1..]. */
  rankByWeek: number[];
  investmentReturn: number;
  maxDrawdown: number;
  betStats: {
    count: number;
    stakedCents: Cents;
    payoutCents: Cents;
    /** Net winnings from parlay + longshot tickets only. */
    parlayNetCents: Cents;
  };
  /** True strength of the drafted roster (optimal lineup by true means). */
  oracleStrength: number;
}

export interface SeasonResult {
  config: SeasonConfig;
  teams: TeamSeason[];
}

export function runSeason(cfg: SeasonConfig): SeasonResult {
  if (cfg.botKeys.length !== cfg.nTeams) throw new Error('botKeys must have one entry per team');
  const rng = new Rng(cfg.seed);

  // --- league setup ---
  const pool = generatePlayerPool(rng.child('pool'));
  const playerById = new Map(pool.map((p) => [p.id, p]));
  const bots: StrategyBot[] = cfg.botKeys.map((k) => {
    const b = BOT_BY_KEY.get(k);
    if (!b) throw new Error(`unknown bot: ${k}`);
    return b;
  });
  const teams: FantasyTeam[] = bots.map((b, i) => ({
    id: `T${i + 1}`,
    name: `${b.name} ${i + 1}`,
    roster: [],
  }));
  const teamIds = teams.map((t) => t.id);

  // Fantasy skill is independent of investing style: scouting errors are drawn
  // and then shuffled so bot archetype does not correlate with roster quality.
  const skillRng = rng.child('skill');
  const scoutingError = skillRng.shuffle(teams.map((_, i) => 0.05 + (0.25 * i) / (cfg.nTeams - 1)));
  runSnakeDraft(teams, pool, { scoutingError }, rng.child('draft'));

  const schedule = buildSchedule(teamIds, cfg.weeks);
  const listedPlayers = [...pool]
    .sort((a, b) => b.projection - a.projection)
    .slice(0, cfg.listedPlayerCount);
  const market = new Market({
    listedPlayers,
    totalWeeks: cfg.weeks,
    maxDecimalOdds: cfg.maxDecimalOdds ?? null,
  });

  // Betting caps are enforced by the Portfolio itself (the server-side boundary).
  const portfolios = new Map<string, Portfolio>(
    teamIds.map((id) => [id, new Portfolio(id, { maxOpenStakeFractionOfNav: cfg.bettingCapPct })]),
  );
  if (cfg.startingBankrollCents > 0) {
    for (const p of portfolios.values())
      p.deposit(0, cfg.startingBankrollCents, 'starting bankroll');
  }

  // Managers set lineups by blending preseason projections with what players
  // have actually done (they learn as the season goes).
  const realizedAvg = new Map<string, number>(pool.map((p) => [p.id, p.projection]));
  const perceived = (p: NflPlayer): number =>
    0.5 * p.projection + 0.5 * (realizedAvg.get(p.id) ?? p.projection);

  const results: MatchupResult[] = [];
  const capitalGenerated = new Map<string, Cents>(teamIds.map((id) => [id, 0]));
  const navByWeek = new Map<string, Cents[]>(
    teamIds.map((id) => [id, [cfg.startingBankrollCents]]),
  );
  const rankByWeek = new Map<string, number[]>(teamIds.map((id) => [id, []]));
  const offerKind = new Map<string, BetKind>();
  const scoreRng = rng.child('scores');
  const botRng = rng.child('bots');

  for (let week = 1; week <= cfg.weeks; week++) {
    // 1. slate opens
    const offers = market.openWeek(week, rng);
    for (const o of offers) offerKind.set(o.id, o.kind);

    // 2. managers act on prior information
    const navsEntering = teamIds.map((id) => (portfolios.get(id) as Portfolio).navCents(market));
    const leaderNav = Math.max(...navsEntering);
    const order = botRng.child(`order-${week}`).shuffle(teamIds.map((_, i) => i));
    for (const i of order) {
      const teamId = teamIds[i] as string;
      const myNav = navsEntering[i] as Cents;
      const ctx: BotContext = {
        week,
        weeksTotal: cfg.weeks,
        rng: botRng.child(`act-${week}-${teamId}`),
        portfolio: portfolios.get(teamId) as Portfolio,
        market,
        offers,
        bettingCapPct: cfg.bettingCapPct,
        desperationEnabled: cfg.desperationEnabled,
        myRank: 1 + navsEntering.filter((n) => n > myNav).length,
        leaderNavCents: leaderNav,
        nTeams: cfg.nTeams,
      };
      (bots[i] as StrategyBot).act(ctx);
    }

    // 3. games are played
    const weekPoints = new Map<string, number>();
    for (const p of pool) weekPoints.set(p.id, samplePlayerWeek(p, scoreRng));

    const teamScore = (team: FantasyTeam): number => {
      const roster = team.roster.map((id) => playerById.get(id) as NflPlayer);
      const lineup = optimalLineup(roster, perceived);
      let score = 0;
      for (const player of lineup.values()) score += weekPoints.get(player.id) ?? 0;
      return Math.round(score * 10) / 10;
    };

    for (const m of schedule.filter((x) => x.week === week)) {
      const home = teams.find((t) => t.id === m.homeTeamId) as FantasyTeam;
      const away = teams.find((t) => t.id === m.awayTeamId) as FantasyTeam;
      const homeScore = teamScore(home);
      const awayScore = teamScore(away);
      // Ties go to the home team (documented; ties are ~1-in-1000 with 0.1 rounding).
      const winnerTeamId = homeScore >= awayScore ? home.id : away.id;
      results.push({ ...m, homeScore, awayScore, winnerTeamId });

      for (const [team, score] of [
        [home, homeScore],
        [away, awayScore],
      ] as const) {
        const won = winnerTeamId === team.id;
        const capital = weeklyCapital(score, won, cfg.formula);
        (portfolios.get(team.id) as Portfolio).deposit(week, capital, `week ${week} capital`);
        capitalGenerated.set(team.id, (capitalGenerated.get(team.id) as Cents) + capital);
      }
    }

    for (const p of pool) {
      const prev = realizedAvg.get(p.id) as number;
      realizedAvg.set(p.id, 0.7 * prev + 0.3 * (weekPoints.get(p.id) as number));
    }

    // 4. markets realize the week
    const outcome = market.stepWeek(weekPoints, rng);
    for (const portfolio of portfolios.values()) {
      for (const [assetId, perShare] of outcome.dividendsPerShare) {
        portfolio.applyDividend(week, assetId, perShare);
      }
      portfolio.settleWeek(week, outcome.betOutcomes);
      portfolio.checkInvariants(market);
    }

    // 5. snapshot
    const navs = teamIds.map((id) => (portfolios.get(id) as Portfolio).navCents(market));
    for (let i = 0; i < teamIds.length; i++) {
      const id = teamIds[i] as string;
      const nav = navs[i] as Cents;
      (navByWeek.get(id) as Cents[]).push(nav);
      (rankByWeek.get(id) as number[]).push(1 + navs.filter((n) => n > nav).length);
    }
  }

  // --- final report ---
  const standings = computeStandings(teamIds, results);
  const standingsById = new Map(standings.map((s) => [s.teamId, s]));

  const teamSeasons: TeamSeason[] = teams.map((team, i) => {
    const portfolio = portfolios.get(team.id) as Portfolio;
    const row = standingsById.get(team.id);
    if (!row) throw new Error(`missing standings for ${team.id}`);
    const navs = navByWeek.get(team.id) as Cents[];
    const roster = team.roster.map((id) => playerById.get(id) as NflPlayer);
    const oracleLineup = optimalLineup(roster, (p) => p.trueMean);
    let oracleStrength = 0;
    for (const p of oracleLineup.values()) oracleStrength += p.trueMean;

    let count = 0;
    let stakedCents = 0;
    let payoutCents = 0;
    let parlayNetCents = 0;
    const stakeByBet = new Map<string, Cents>();
    for (const e of portfolio.ledger) {
      if (e.kind === 'BET_PLACED') {
        count++;
        stakedCents += e.stakeCents;
        stakeByBet.set(e.betId, e.stakeCents);
      } else if (e.kind === 'BET_SETTLED') {
        payoutCents += e.payoutCents;
        const kind = offerKind.get(e.betId);
        if (kind === 'parlay' || kind === 'longshot') {
          parlayNetCents += e.payoutCents - (stakeByBet.get(e.betId) ?? 0);
        }
      }
    }

    return {
      teamId: team.id,
      teamName: team.name,
      botKey: (bots[i] as StrategyBot).key,
      wins: row.wins,
      losses: row.losses,
      pointsFor: Math.round(row.pointsFor * 10) / 10,
      capitalGeneratedCents: capitalGenerated.get(team.id) as Cents,
      finalNavCents: navs[navs.length - 1] as Cents,
      navByWeek: navs,
      rankByWeek: rankByWeek.get(team.id) as number[],
      investmentReturn: portfolio.investmentReturn(market),
      maxDrawdown: maxDrawdown(navs),
      betStats: { count, stakedCents, payoutCents, parlayNetCents },
      oracleStrength: Math.round(oracleStrength * 10) / 10,
    };
  });

  return { config: cfg, teams: teamSeasons };
}

function maxDrawdown(navs: readonly Cents[]): number {
  let peak = -Infinity;
  let worst = 0;
  for (const nav of navs) {
    if (nav > peak) peak = nav;
    if (peak > 0) worst = Math.max(worst, (peak - nav) / peak);
  }
  return worst;
}
